### ISSUE TITLE
Bug: Unable to remove PoTree Camera Animations

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1025]
STR:
1. Create project with pointcloud
2. Add default camera animation
3. Add more
4. Select animation and delete key frames
5. See that empty animations can not be purged
6. (Possible breakage of PoTree view from above steps that persists across app instances)

**Comment by pierotofy** [comment]
Hi @Saijin-Naib,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-07-28 01:00) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
