### ISSUE TITLE
Dynamic 'Share' link genration

### ISSUE THREAD

**Issue by arpitpara** [OpenDroneMap/WebODM#1032]
Platform - WebODM windows 10 Pro Native

Issue:
I'm using the REST API services of 'WebODM' to create project and tasks. I'm getting a ' task_id ' in the process of this. 
![Screenshot (110)](https://user-images.githubusercontent.com/58958058/128349200-b3398853-22be-4858-a1d6-1c78c7bd26b1.png)

URL = http://127.0.0.1:29800/public/task/task_id/map/
But this link won't work till I click on the 'Share' button to generate the link on 'View Map' feature on that particular task first.

I want either this link to be generated from the REST API itself or activated 'by default' from the code after completion of the task.

**Comment by pierotofy** [comment]
Hi @arpitpara,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-08-06 08:30) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by arpitpara** [comment]
Browser info:
https://whatismybrowser.com/w/8PENN9T
