### ISSUE TITLE
How do I set a password or permission for the front-end view?

### ISSUE THREAD

**Issue by carveybunt** [OpenDroneMap/WebODM#1052]
First of all, thanks to your team.
I've been successfully using WebODM via Docker on mac 10.13. 
But I wanna set a password or assign permission for the front-end view, if the project supports how do I?

**Comment by pierotofy** [comment]
Hi @carveybunt,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-09-06 09:20) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
