### ISSUE TITLE
Edit short links plugin not working for specific users with periods in username

### ISSUE THREAD

**Issue by OKaluza** [OpenDroneMap/WebODM#1076]
Hi Piero, I notice in the editshortlinks plugin, periods are not allowed in user names:

https://github.com/OpenDroneMap/WebODM/blob/9e4c626d423d4d62aac40051e7e2a5f191bfb752/coreplugins/editshortlinks/plugin.py#L16

This is an issue for us as our social auth setup tends to create user names of the format Firstname.Lastname by default.

I've removed . from the excluded chars in the regex on our instance and things seem to work, but just want to know I'm not going to break something.

**Comment by pierotofy** [comment]
Hi @OKaluza,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-10-21 00:35) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
