### ISSUE TITLE
ODM docker as base image does not work on sagemaker 

### ISSUE THREAD

**Issue by karankatiyar92** [OpenDroneMap/WebODM#1083]
hi all ,
i am trying to run odm as base image ( basically wrote the code on top of odm as base image to download data and then call run.py ) . i am using ml.m5d.24xlarge instance . input data is 600 mbs around 66 images . same code ( with odm as base image and my code on top of it )  runs fine as a docker on local . i am not sure what is the issue when i deploy the same on sagemaker . please find attached screenshot and suggest what can be done for the same to fix it . the command i am using is python run.py (it basically tries to give all feasible outputs ( i dont think that is the issue bcz it runs perfectly fine on local ) . i am using odm 2.5.1 image .  )( the results directory of odm are stored in /mnt directory of the docker ) 
![image](https://user-images.githubusercontent.com/18509764/139496748-599d8780-9bbd-4f21-b85b-11699cda116f.png)
![image](https://user-images.githubusercontent.com/18509764/139496866-e0ec89e7-b329-4ab0-9b99-2d5527950b84.png)

it also gives child returned 134  error

**Comment by pierotofy** [comment]
Hi @karankatiyar92,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-10-30 16:25) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
