### ISSUE TITLE
Lightning node is hung while resizing images

### ISSUE THREAD

**Issue by konradkern** [OpenDroneMap/WebODM#1127]
I installed my version with the WebODM installer. It is installed on my desktop.   It has worked well for some time.  

I'm using Chrome

The processor has hung both times at the resizing images step.  The circling busy button keeps spinning, The process completion bar goes forward and then resets.   

This may be simple like restarting the lightning server.  I have submitted the same job twice.  The job is large-ish (345 images) and it has a GCP file.    

 I had to halt the job once and may not have allowed the server to close properly.  The job is 220119_sky1_GCP in my account.  Can you help?

**Comment by pierotofy** [comment]
Hi @konradkern,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2022-01-26 11:20) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Hey @konradkern :hand: if it's stuck at "resizing" then it's probably something stuck on your local machine, not on the Lightning server. Do you have enough free disk space?

**Comment by konradkern** [comment]
I thank you.  Yes, I have gobs of Ram and disk space.  I've run my computer
cleaner and restarted after I aborted the jobs.  I'm sure it will resolve
in time.

Konrad
ph 714-658-4972
