### ISSUE TITLE
Generate map tiles for 10-14 zoom levels

### ISSUE THREAD

**Issue by spatialhast** [OpenDroneMap/WebODM#114]
Now min zoom level for overlay layer (orthophotos) is 15. Please add option generation map tiles from 12 zoom level.

**Comment by pierotofy** [comment]
I've added 12 as a start level on node-odm. https://github.com/OpenDroneMap/node-OpenDroneMap/commit/970efa2d6da0e354c661a2b73dede8cbda70fa92

If you upgrade your processing node you should be able to generate tiles for 12 zoom level.

You must be processing fairly large areas :) Would you be able to share how you are currently using WebODM? I'm just interested in hearing more about how the software is being used, so that I can focus my efforts on the features users care about.
