### ISSUE TITLE
Different synthesis results for the same task with the same parameters

### ISSUE THREAD

**Issue by LeeLulin** [OpenDroneMap/WebODM#1215]
How did you install WebODM (docker, installer, etc.)?
docker

What's your browser and operating system?
Edge 103 on macOS (Catalina)

What is the problem?
There are about 160 images for orthophoto synthesis, and with fast orthophoto on with constant parameters, the synthesized orthophoto impact will be distorted with a high probability after each restart from the dataset, and the results will be different each time. There is a chance that it will work after several reboots.

![11](https://user-images.githubusercontent.com/27431274/181404130-892777bb-627a-435b-88bd-f80192c04001.png)

<img width="889" alt="22" src="https://user-images.githubusercontent.com/27431274/181404155-766a7927-476e-44a2-a806-a025b19e2d78.png">

How can we reproduce this?
Open fast-orthophoto only, resturn from the dataset, and view the synthesis results
Dataset: https://hub.dronedb.app/r/lulin/test

**Comment by pierotofy** [comment]
The linear pattern of the dataset (no sidelap, fixed altitude) is probably throwing off the reconstruction.

I'd suggest to process using `--fast-orthophoto --sfm-algorithm planar`, which is less susceptible to linear pattern. I got a nice orthophoto using these two parameters:

![image](https://user-images.githubusercontent.com/1951843/181412469-34bf2464-1429-4d89-9f70-a74625f554fa.png)

https://hub.dronedb.app/r/pierotofy/flafoju5lvl6ro7f

Also make sure you're using the latest version and note that results will not always be the exactly the same due to randomness in the underlying algorithms.
