### ISSUE TITLE
The message "You can read more about best practices for capturing good images" points to an invalid URL

### ISSUE THREAD

**Issue by MarcelvandenAker** [OpenDroneMap/WebODM#1234]
How did you install WebODM (docker, installer, etc.)?
Using "WebODM_Setup" 

What's your browser and operating system?
https://www.whatismybrowser.com/w/QMTPK9D

What is the problem?
this link is invalid => https://support.dronedeploy.com/v1.0/docs/making-successful-maps)

How can we reproduce this?
There is a small help text that points to an incorrect URL
The text is: "You can read more about best practices for capturing good images [here](https://support.dronedeploy.com/v1.0/docs/making-successful-maps)"

**Comment by pierotofy** [comment]
Hi @MarcelvandenAker,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2022-09-09 08:20) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
