### ISSUE TITLE
Python 2 or 3?

### ISSUE THREAD

**Issue by vesnikos** [OpenDroneMap/WebODM#13]
Before the project proceeds any further I would like to ask the developers which version of python the would consider using?

I would opt for python 3 as in my experience I see python 2 being slowly phased out in favor of 3 and virtually all  geospatial libraries now they providing support for it. 

Thoughts?

**Comment by dakotabenjamin** [comment]
OpenDroneMap is in Python 2 so in the short term we should stick with that.

**Comment by pierotofy** [comment]
I want badly to use Python 3, but the reason I've initially setup WebODM to use the 2.7 image is because I don't yet know for sure what libraries we are going to need (and which ones perhaps we can work around, or substitute). There seems to be quite a big of fragmentation still going on as of today, many packages simply do not work in 3.

My take was to develop using Python 2, making sure to follow Django's best practices for compatibility: https://docs.djangoproject.com/en/1.10/topics/python3/. Then as soon as we have a good idea of what libraries we are using, check if they work on Python 3, and make the switch.

@vesnikos do you foresee any problem in using Python 3 directly? I would like to take a gamble and start targeting 3 directly, I just don't know all of the requirements of the project at this point.

**Comment by pierotofy** [comment]
Opened #16

**Comment by smathermather** [comment]
Ah, ya. I forgot about his one.

**Comment by pierotofy** [comment]
Switched to Python 3, see #16
