### ISSUE TITLE
Geodesic coordinate transformation

### ISSUE THREAD

**Issue by konradkern** [OpenDroneMap/WebODM#1304]
### What is the problem?

When you wish to output a TIF in different coordiante reference system, the transformation process doesn't perform a geodesic transform.  If you're using GDALWARP to change CRS, you musts use a explicit transform with the -ct command and supply the WKT  
version of the CRS  Using the -s_srs and -t_srs with the new and old EPSG  only performs a cartesian transformation and will be about a meter in error 

My examples are available here
https://drive.google.com/drive/folders/1Ciql4dD07yUONFYHxq5DKH8IkyJQs6Ck?usp=share_link

Thank you in advance

Konrad

**Comment by pierotofy** [comment]
Hi @konradkern,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2023-03-21 11:00) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue providing **all** required information.
