### ISSUE TITLE
Can't find GeoTiff viewer

### ISSUE THREAD

**Issue by ZulluBalti** [OpenDroneMap/WebODM#1330]
Hi, I've just downloaded this repository and install it via docker. It all works. 

The only problem I'm facing is that I can't find any place in the app (web: localhost:8000) where I can upload .tif files and render it on top of a satellite map.

As we can see in the screen shot
![WebODM-Drone-Software-OpenDroneMap](https://user-images.githubusercontent.com/60227154/234510420-1fc43ffa-3996-4aae-950e-ed531c79a402.png)

**Comment by pierotofy** [comment]
Hi @ZulluBalti,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2023-04-27 04:05) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
