### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by WildcatOne** [OpenDroneMap/WebODM#301]
Trying to process 138 images, and after 4 hours, it fails.
Any ideas? here is the message:
Created on: 10/13/2017, 1:43:54 PM
Status: Failed
Options: mesh-octree-depth: 12, min-num-features: 8000, orthophoto-resolution: 60, dem-resolution: 0.04, use-exif: true, skip-resize: true, dsm: true, use-25dmesh: true

2017-10-13 19:54:13,486 Merging depthmaps

Traceback (most recent call last):
  File "/code/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 128, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137

**Comment by WildcatOne** [comment]
Here are the images if anyone wants them.
https://www.dropbox.com/sh/b9avcja8itzml6o/AADebNZWA13rMMuH-In2Be0Ta?dl=0

**Comment by smathermather** [comment]
Do they have gps in the exif tags?

**Comment by WildcatOne** [comment]
Yes, they do.
![exif](https://user-images.githubusercontent.com/29640325/31611092-b365ce2a-b248-11e7-9dbd-8e7db350b55f.PNG)

**Comment by pierotofy** [comment]
Hi, this might be a problem related to memory usage. What happens if you reduce `min-num-features` to 4000 and remove `skip-resize`? Also, could you share some information about your system (amount of RAM, CPU, operating system, are you running with docker, how much memory have you allocated to the docker VM, etc.)?
