### ISSUE TITLE
Process completed but isn't good.

### ISSUE THREAD

**Issue by cfdar** [OpenDroneMap/WebODM#355]
How did you install WebODM? (Docker, natively, ...)?

Docker

What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 62 on Windows 10

What is the problem?

 I made a process and the result wasnt good, the roofs are curv. 

What should be the expected behavior?

I need Help

How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
"Options: mesh-octree-depth: 12, min-num-features: 8000, orthophoto-resolution: 60, dem-resolution: 0.04, dsm: true, use-25dmesh: true, use-pmvs: true"
In the link to google drive have the individual images, the ortomosaic results from WebODM and other i procesed with dronedeploy. [https://drive.google.com/drive/folders/1A6yRorRe1uReqf6NmnYhRqxsD2h2imxF?usp=sharing](url)

**Comment by pierotofy** [comment]
Hi @cfdar,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2017-12-09 08:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Hey @cfdar, try to remove the use-25dmesh option from your preset.

**Comment by cfdar** [comment]
Hi @pierotofy , i removed the use-25dmesh option, and the result was better, but isn't good like drone deploy, the roofs are stiil curved, less than before, and the vegetation looks like blurred. Do you have a default parameters for images from urban area ou vegetation area?

Where can i find a manual with details about task option from WebODM?

**Comment by pierotofy** [comment]
Here's a Wiki page on the task options: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Run-Time-Parameters

We are constantly working to improve the quality of the outputs, so keep an eye on the latest developments.
