### ISSUE TITLE
node-odm-1:3000 seems to be offline

### ISSUE THREAD

**Issue by rdmhora** [OpenDroneMap/WebODM#374]
Hello, 

I've been using WebODM in docker for Mac without any problem until I upgraded Docker. I tried to re-install docker and WebODM but didn't Work. 
Can anyone help me please.

Version 17.12.0-ce-mac47 (21805)

<img width="1373" alt="captura de tela 2018-01-17 as 16 30 41" src="https://user-images.githubusercontent.com/34491928/35059956-07cfdef2-fba4-11e7-944c-75915bbb3802.png">

<img width="1223" alt="captura de tela 2018-01-17 as 16 32 18" src="https://user-images.githubusercontent.com/34491928/35059982-18c4f7e2-fba4-11e7-9459-4c89f1d21197.png">

<img width="1373" alt="captura de tela 2018-01-17 as 16 31 14" src="https://user-images.githubusercontent.com/34491928/35059986-1c418bba-fba4-11e7-9386-beb9badba67a.png">

**Comment by pierotofy** [comment]
Hi @rdmhora,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-01-20 13:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
