### ISSUE TITLE
Issue running ODM

### ISSUE THREAD

**Issue by TheVidar** [OpenDroneMap/WebODM#401]
We are experiencing the following issue when running around 250 images

l2d_dems dtm completed (../var/www/data/5737efc3-aead-41c4-8c92-814e53d60ff9/odm_dem) in 0:00:37.768106
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_dem.py", line 142, in process
    os.rename(os.path.join(odm_dem_root, dtm_pattern), dtm_output_filename)
OSError: [Errno 2] No such file or directory

Could anyone point me in the right direction?

**Comment by pierotofy** [comment]
Hi @TheVidar,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-02-24 08:20) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
