### ISSUE TITLE
Reference plane for volume calculation

### ISSUE THREAD

**Issue by taoansf** [OpenDroneMap/WebODM#429]
How did you install WebODM? (Docker, natively, ...)?
[I purchased the installer]
What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
[Edge 41 on Windows 10]
What is the problem?
[I'm a new user of WebODM and I would like to calculate the volume of a hole in my surface model. My problem is that I can't find an option to select if the volume is calculated below or above my reference plane. I'm supposing that WebODM uses the evelation of the boundaries of my calculation polygon as the reference plane? 
This site explain better my question
http://desktop.arcgis.com/en/arcmap/10.3/tools/3d-analyst-toolbox/surface-volume.htm]
What should be the expected behavior?
[I think that option could be very useful when you need to calculate the volume in different situations. For example, calculate the volume that fill a hole (below the reference plane) or a volume of a hill (above my reference plane)]
How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
[Check the interface for volume calculation]

**Comment by pierotofy** [comment]
Hi @taoansf,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-04-13 14:55) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
@taoansf the reference plane is interpolated from the polygon boundaries (only from the points you click on the map). Then the reference plane is subtracted from the digital surface model of the area. We always return the absolute value of the difference between the reference plane and the DSM, so it shouldn't matter whether you are measuring a hole or a volume. 

The full script is available here: https://github.com/OpenDroneMap/WebODM/blob/master/plugins/measure/calc_volume.grass

**Comment by taoansf** [comment]
thank you, got it
cheers!
