### ISSUE TITLE
MANUAL O TUTORIAL

### ISSUE THREAD

**Issue by EddisonJose** [OpenDroneMap/WebODM#447]
Hola, solo para saber ya que no encuentro: Hay un manual - tutorial de como usar WEBODM? muchas gracias, Eddison

**Comment by pierotofy** [comment]
Hi @EddisonJose,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-05-11 09:25) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by EddisonJose** [comment]
Hola, muchas gracias y disculpe mi error, saludos

**Comment by smathermather** [comment]
As this is posted in the community forum now, I'll close it. Thanks @EddisonJose!
