### ISSUE TITLE
WebODM Not connecting when I change from one network to another

### ISSUE THREAD

**Issue by cmjspider** [OpenDroneMap/WebODM#464]
Hi when I use my mobile wifi to log into ODM it works fine,
When I get home and connect to my home wifi the ip stays red and I can not access ODM can anyone help with this, 

Thank you

                           [04]: Hyper-V Virtual Ethernet Adapter
                           [05]: Hyper-V Virtual Ethernet Adapter
                           [06]: Hyper-V Virtual Ethernet Adapter
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
Detected Windows 10 with Hyper-V support
Initializing console...
Checking if current user is in docker-users group
User is in docker-users group
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
7fdc89fcae82        redis               "docker-entrypoint.sâ€¦"   5 minutes ago       Up 5 minutes        6379/tcp            broker
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
Press Start WebODM to launch
Checking for MS Edge Zone...
Zones are OK
Press Start WebODM to launch
C:\WebODM Manager>cd WebODM/ 
C:\WebODM Manager\WebODM>docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml start   || docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up 
Starting db         ... 
Starting node-odm-1 ... 
Starting broker     ... 
Starting worker     ... 
Starting webapp     ... 
[3A[2K
Starting broker     ... [32mdone[0m
[3B[4A[2K
Starting node-odm-1 ... [31merror[0m
[4B[1A[2K
Starting webapp     ... [31merror[0m
[1B[5A[2K
Starting db         ... [31merror[0m
[5B[2A[2K
Starting worker     ... [31merror[0m
[2B
ERROR: for node-odm-1  Cannot start service node-odm-1: driver failed programming external connectivity on endpoint node-odm-1 (769e43837cc6a8a9a95056f46a87496e6165cc977a22b73809acd2eb02a95cd5): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32837:tcp:172.18.0.3:3000: input/output error
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint db (072a3bc4268ca4af12576c281c7556e6f6b967ac0d82bbf82eb5aeaf144c8f3e): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32839:tcp:172.18.0.4:5432: input/output error
C:\WebODM Manager\WebODM>exit 0 
WebODM has started. You can close this window now. WebODM will continue running.

**Comment by pierotofy** [comment]
Hi @cmjspider,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-06-15 12:45) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
