### ISSUE TITLE
How to share my aerial 3D model to another

### ISSUE THREAD

**Issue by ben0756** [OpenDroneMap/WebODM#495]
Dears
I finished  3d photo modeling but how can I share it with my friends...
The link on WebODM is useless and cannot be opened on a phone or ipad
How can I share my 3d model with WeChat or whatapp???
![default](https://user-images.githubusercontent.com/41659763/43444332-113cbda4-94d6-11e8-94d0-1e68e5445a78.png)

**Comment by pierotofy** [comment]
Hi @ben0756,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-08-03 03:25) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
