### ISSUE TITLE
image resize functionality and pyexiv2

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/WebODM#520]
initially posted at http://community.opendronemap.org/t/an-orthophoto-could-not-be-generated/1018

### How did you install WebODM? (Docker, natively, ...)?
Testing WebODM installed as part of a [POSM install](https://github.com/posm/posm-build/releases) on an Intel NUC Skull Canyon running Ubuntu 18.04 

### What's your browser and operating system?
Chrome 69 on macOS (High Sierra)

### What is the problem?
Ran this dataset (2.2 GB, 434 images taken with a DJI Mavic Pro): https://arcimagery.s3.amazonaws.com/drone_amcross/20170514-palanog.zip
and got the following error:
> An orthophoto could not be generated. To generate one, make sure GPS information is embedded in the EXIF tags of your images, or use a Ground Control Points (GCP) file.

Full processing [log](https://gist.github.com/danbjoseph/f3a27c1aeb6ab0f8f6835c1a2e17e5cb).

I have processed the dataset successfully before. Mid 2017 I think with a native install of ODM on an Intel NUC Skull Canyon.

I think could possibly be the same issue with some of the GPS altitude for the images being off as described here:  http://community.opendronemap.org/t/mapir-survey3-orthophoto-can-not-be-generated/313

The non-georeferenced image looks good.
<img width="1077" alt="screen shot 2018-09-07 at 7 47 43 am" src="https://user-images.githubusercontent.com/4806884/45499725-f7f08c80-b74a-11e8-8d39-e00e97d9d333.png">

The log has this line:
```plain
[DEBUG]   Loaded 20170514_M100_DJI_0177.JPG | camera: dji fc220 | dimensions: 2048 x 1536 | focal: 4.73 | ccd: 6.17 | lat: None | lon: None | alt: None
```
But oddly the file looks like it has the GPS data.

@pierotofy noted:
> Seems like the EXIF tags are not being properly read. 
> This seems to be caused by WebODM’s image resize functionality. A workaround currently is to set the Image Resize option to “Skip” instead of “Yes” when creating a task. Seems to only affect `20170514_M100_DJI_0177.JPG`.
> This is `pyexiv2`'s fault https://github.com/OpenDroneMap/OpenDroneMap/blob/master/opendm/types.py#L60 probably because it’s linked to the older version of `exiv2`. It’s probably related to the issue we’ve encountered with https://github.com/OpenDroneMap/OpenDroneMap/issues/880
> `exiftool` has no problem reading WebODM’s resized image:
> ```
> exiftool resized.jpg
> GPS Altitude                    : 140.3 m Above Sea Level
> GPS Latitude                    : 11 deg 15' 12.30" N
> GPS Longitude                   : 124 deg 57' 11.50" E
> GPS Position                    : 11 deg 15' 12.30" N, 124 deg 57' 11.50" E
> ```

### What should be the expected behavior?
Expected that a georeferenced image output is created.

**Comment by pierotofy** [comment]
Hi @danbjoseph,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2018-09-16 11:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
