### ISSUE TITLE
native install with splitmerge-ecto fails

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/WebODM#598]
### How did you install WebODM? (Docker, natively, ...)?

ran `bash configure.sh install` on AWS EC@ - Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-076e276d85f524150 (64-bit x86) with `splitmerge-ecto`  https://github.com/OpenDroneMap/ODM/commit/3eac0c7048940e815b3fa7a2d7d9f1434295f9ba

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

see above

### What is the problem?

ended with
```
...
-- Configuring incomplete, errors occurred!`
```
- [install-output-log.txt](https://github.com/OpenDroneMap/WebODM/files/2753530/install-output-log.txt)
- [CMakeError.log](https://github.com/OpenDroneMap/WebODM/files/2753532/CMakeError.log)
- [CMakeOutput.log](https://github.com/OpenDroneMap/WebODM/files/2753533/CMakeOutput.log)

### What should be the expected behavior?

it should install. running `sudo bash configure.sh reinstall` on `master` completes without error.
```
...
[100%] Linking CXX executable ../../bin/odm_georef
[100%] Built target odm_georef
Configuration Finished
```

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

see above

**Comment by pierotofy** [comment]
Hi @danbjoseph,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-01-16 16:00) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by danbjoseph** [comment]
apologies. logged this on the wrong repository.

**Comment by smathermather** [comment]
It’s easy to tell as Piero has his bots managing the ones he’s started... :).
