### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by marcosalexan** [OpenDroneMap/WebODM#624]
estou com o seguinte problema abaixo, alguém pode me ajudar?
Start interactive shell

marco@DESKTOP-H1VLNEQ MINGW64 /c/Program Files/Docker Toolbox
$ git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input
fatal: could not create work tree dir 'WebODM': Permission denied

marco@DESKTOP-H1VLNEQ MINGW64 /c/Program Files/Docker Toolbox
$

**Comment by pierotofy** [comment]
Hi @marcosalexan,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-02-18 21:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
