### ISSUE TITLE
Texturing exited with code 1 - Segmentation Fault

### ISSUE THREAD

**Issue by orcunbaslak** [OpenDroneMap/WebODM#654]
**How did you install WebODM? (Docker, natively, ...)?**
Installed via docker.
git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input --depth 1
Running in a Debian9 VM on MacOS

**What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)**
Chrome 73 on macOS (Mojave)

**What is the problem?**
Segmentation Fault while Texturing

**What should be the expected behavior?**
It should pass texturing and move on to georeferencing.

**How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)**

Download Link : https://drive.google.com/open?id=18akK_nhxhhYxPg--Lh2qlxdGueLsqqL_

Updated the software via ./webodm.sh update and running the latest version as of now.

Here's my config.

Created on: 4/21/2019, 9:43:58 PM
Processing Node: node-odm-1:3000 (auto)
Options: min-num-features: 8000, rerun-from: mvs_texturing, orthophoto-resolution: 200, dem-resolution: 5, opensfm-depthmap-min-consistent-views: 4, use-exif: true, dem-decimation: 80, dsm: true, texturing-keep-unseen-faces: true, pc-csv: true

Error Output:
[SegFaultDetails.txt](https://github.com/OpenDroneMap/WebODM/files/3101512/SegFaultDetails.txt)

**Comment by pierotofy** [comment]
Hi @orcunbaslak,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-04-24 15:00) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by orcunbaslak** [comment]
Hello @pierotofy ,
Just updated according to the template.

**Comment by pierotofy** [comment]
It's been a while since this was opened, and we made some major improvements to ODM. Could you try to reprocess with the latest version and see if the issue persists? If so, feel free to reopen this one. :+1:
