### ISSUE TITLE
Cesium Ion 

### ISSUE THREAD

**Issue by ProjectBarks** [OpenDroneMap/WebODM#677]
Hi WebODM team! I am currently working on a cesium add that will allow for viewing of assets in the cesium environments. I was hoping to make this into a pull request so it becomes a part of the project. My hopes are I can get feedback before I put time in.

## Planned Features
* Viewing in the cesium viewer with measurement tools
* Upload to ion for distributing model to other platforms 

Just let me know any thoughts or if this would be something of interest.

**Comment by pierotofy** [comment]
Hi @ProjectBarks,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-06-17 13:50) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
