### ISSUE TITLE
Error in starting WebODM.sh

### ISSUE THREAD

**Issue by rmbasina** [OpenDroneMap/WebODM#708]
rmbasina@rmbasina MINGW64 /c/webODM (master)
$ ./webODM.sh test
grep: /proc/1/cgroup: No such file or directory
Running tests in webapp container
docker-compose exec webapp /bin/bash -c "/webodm/webodm.sh test"
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

**Comment by pierotofy** [comment]
Hi @rmbasina,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-08-02 08:45) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
