### ISSUE TITLE
Can't start WEBODM

### ISSUE THREAD

**Issue by dwpeters1** [OpenDroneMap/WebODM#739]
I have tried several times to open Web ODM but it gets stuck at the following place in the process
<img width="519" alt="Screen Shot 2019-10-10 at 11 11 03 AM" src="https://user-images.githubusercontent.com/55260866/66586804-e268b480-eb4e-11e9-96b7-f87c587ade8d.png">

**Comment by pierotofy** [comment]
Hi @dwpeters1,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-10-13 12:15) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
