### ISSUE TITLE
Wrong export coordinates WebODM

### ISSUE THREAD

**Issue by gabiborlea** [OpenDroneMap/WebODM#743]
I created a 3dModel with webodm. I created a gcpfile and i uploaded it with the pictures. I selected from options the csv point cloud option. When I wanted to export the csv file the coordinates were wrong. Then I checked the las file and the coordinates were wrong ass well. The opthopohoto seems to be placed fine. 
![gagga](https://user-images.githubusercontent.com/57035818/67618903-e3ac0980-f7fd-11e9-8251-5c12df46fc6a.png)
there is the gcp file
[gcp_file_1570379154839.txt](https://github.com/OpenDroneMap/WebODM/files/3774763/gcp_file_1570379154839.txt)
but there is a part of the csv file and the coordinates are totally off
[Book1.txt](https://github.com/OpenDroneMap/WebODM/files/3774767/Book1.txt)

[orthophoto_tiles (1).zip](https://github.com/OpenDroneMap/WebODM/files/3774768/orthophoto_tiles.1.zip)

**Comment by pierotofy** [comment]
Hi @gabiborlea,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-10-29 07:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
