### ISSUE TITLE
requirements.txt need to be updated

### ISSUE THREAD

**Issue by rumenmitrev** [OpenDroneMap/WebODM#750]
requests-toolbelt==0.8.0
requests==2.20.0

Should become:

requests-toolbelt==0.9.1
requests==2.21.0

**Comment by pierotofy** [comment]
Hi @rumenmitrev,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-11-21 05:55) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by rumenmitrev** [comment]
How did you install WebODM? (Docker, natively, ...)?

natively

What's your browser and operating system? 
ubuntu server 16.04

What is the problem?
When you compile webodm naively it fells because we requested from  requirements.txt
requests-toolbelt==0.8.0
requests==2.20.0

What should be the expected behavior?

if I bump versions of
requests-toolbelt==0.8.0
requests==2.20.0

to 

requests-toolbelt==0.9.1
requests==2.21.0

it compiles and run fine.

**Comment by pierotofy** [comment]
Hey @rumenmitrev :+1: thanks for the report!

Would you be interested in making the change to requirements.txt and open a pull request? https://github.com/OpenDroneMap/WebODM/edit/master/requirements.txt

**Comment by rumenmitrev** [comment]
Will do.
