### ISSUE TITLE
ERROR 6: zoom_level > 22 not supported NodeMICMAC

### ISSUE THREAD

**Issue by rumenmitrev** [OpenDroneMap/WebODM#760]
What's your browser and operating system?
Ubuntu 16.04

What is the problem?
ERROR 6: zoom_level > 22 not supported  NodeMICMAC no point cloud

What should be the expected behavior?
nice looking point cloud in awesome WebODM interface

How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Use NodeMICMAC as processing node.

I will repost the issue as I opened in NodeMICMAC repository ,  because cant figure where is the problem exactly.

https://github.com/dronemapper-io/NodeMICMAC/issues/42#issue-532510714

>  Hello,
> 
> I have manged to compile micmac natively on Ubuntu 16.04.
> And use it via NodeMicmac and WebODM.
> Initially it failed at orthophoto step. I asked in [micmac forum](http://forum-micmac.forumprod.com/micmac-quot-cannot-handle-substitution-quot-t1887.html) and they suggest to replace
> this command in run.py
> 
>` #system.run('{mm3d} Porto Ortho-MEC-Malt/Param-Tawny.xml'.format(**kwargs_malt))`
> 
> whit this:
> 
>` #system.run('{mm3d} Tawny Ortho-MEC-Malt'.format(**kwargs_malt))`
> 
> Now orthophoto and surface models are excellent.
> 
> But it fails at point cloud step with:
> 
> `ERROR 6: zoom_level > 22 not supported`
> 
>` Point cloud tiles will not be generated`
> 
> `Postprocessing: done (•̀ᴗ•́)و!`
> 
>` Compressing all.zip`
> 
>` Done!`
> Actually there is point cloud and if I downloaded, I can open it in Meshlab
> But cant be seen in WebODM , and it fails with:
> "Could not load point cloud. This task doesn't seem to have one. Try processing the task again."
> 
>` bin/mm3d CheckDependencies`
> 
> `Code:`
> `git revision : v1.0.beta13-612-ga2c0eb1`
> 
> `byte order   : little-endian`
> `address size : 64 bits`
> 
>` micmac directory : [/home/drnmppr-micmac/]`
> `auxilary tools directory : [/home/drnmppr-micmac/binaire-aux/linux/]`
> 
>` make:  found (/usr/bin/make)`
> `exiftool:  found (/usr/bin/exiftool)`
>` exiv2:  found (/usr/bin/exiv2)`
> `convert:  found (/usr/bin/convert)`
>` proj:  found (/usr/bin/proj)`
>` cs2cs:  found (/usr/bin/cs2cs)`
>` complete console output`
> 
> EDIT1:
> Actually using docker image `docker run -d -p 3001:3000 dronemapper/node-micmac` produce the same result.` "ERROR 6: zoom_level > 22 not supported"` and no point cloud in WebODM

**Comment by pierotofy** [comment]
Hi @rumenmitrev,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-12-08 07:10) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Thanks @rumenmitrev :+1: I think this might need to be fixed on the NodeMICMAC side.
