### ISSUE TITLE
Merging two or more projects

### ISSUE THREAD

**Issue by hassanyf** [OpenDroneMap/WebODM#772]
Hello!

Is it possible to merge two or more projects? or .obj files in WebODM? I have two different maps and I want to stitch them together. Is this possible or do I have to do it manually using another software such as Blender?

Thanks!

**Comment by pierotofy** [comment]
Hi @hassanyf,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-12-15 02:30) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
