### ISSUE TITLE
does tile in cesium ion still work?

### ISSUE THREAD

**Issue by RussellGrew** [OpenDroneMap/WebODM#853]
### What is the problem?

Cannot use WebODM UI to upload to Cesium Ion

### What should be the expected behavior?

The data set should upload to Cesium Ion.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

After pressing the tile button, the "view ion tasks" button is stuck in upload and the data set never appears in Cesium.

![image](https://user-images.githubusercontent.com/42530666/79942054-4595b500-84a9-11ea-97c4-8b72c7c4f9e5.png)

I have tested API access from this Windows box running Docker as below, and this works fine

```
curl "https://api.cesium.com/v1/assets" -H "Authorization: Bearer <your_access_token>"
```

I am happy to test this inside Docker if you can help with the command sequence.

I have tried creating a new ion token. All asset types (point cloud, texture, orthophoto) will not upload.

Any advice is welcome. 

Thanks.

**Comment by pierotofy** [comment]
Hi @RussellGrew,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2020-04-25 01:05) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
