### ISSUE TITLE
Ubuntu run ./webodm.sh start --dev not sucessed.

### ISSUE THREAD

**Issue by zhishiqu** [OpenDroneMap/WebODM#908]
![image](https://user-images.githubusercontent.com/22735110/92373599-24202780-f131-11ea-9323-a11a6aa40479.png)
It stops every time it gets here。it is not open at url http://localhost:8000. Who can help me。Thanks very much.

**Comment by pierotofy** [comment]
Hi @zhishiqu,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2020-09-10 05:50) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
