### ISSUE TITLE
Parsing wrong GCP SRS header

### ISSUE THREAD

**Issue by SatishAkula91** [OpenDroneMap/WebODM#933]
Hi,

WebODM is parsing a wrong zone number from srs header provide from gcp_list.txt, adding the output log for your reference

[INFO]    Parsing SRS header: +proj=utm +zone=44 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
[INFO]    Generated coords file from GCP: WGS84 UTM 46N
[INFO]    Parsing SRS header: WGS84 UTM 46N
[INFO]    Parsing SRS header: WGS84 UTM 46N
[INFO]    16 GCP points will be used for georeferencing

You can see from the above line the given zone number is 44 but it calculated it as a 46N...
[console.txt](https://github.com/OpenDroneMap/WebODM/files/5522218/console.txt)

**Comment by pierotofy** [comment]
Hi @SatishAkula91,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2020-11-14 01:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
