### ISSUE TITLE
pip install -r requirements.txt cannot found  'rasterio-1.1.3-cp37-cp37m-win_amd64.whl' and 'GDAL-3.0.4-cp37-cp37m-win_amd64.whl'

### ISSUE THREAD

**Issue by china0zzl** [OpenDroneMap/WebODM#934]
pip install -r requirements.txt

ERROR: HTTP error 404 while getting https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.whl
  ERROR: Could not install requirement rasterio==1.1.3 from https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.whl (from -r require
ments.txt (line 60)) because of error 404 Client Error: Not Found for url: https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.whl
ERROR: Could not install requirement rasterio==1.1.3 from https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.whl (from -r requireme
nts.txt (line 60)) because of HTTP error 404 Client Error: Not Found for url: https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.wh
l for URL https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/rasterio-1.1.3-cp37-cp37m-win_amd64.whl

please help me, thanks!

**Comment by pierotofy** [comment]
Hi @china0zzl,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2020-11-15 01:00) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
