### ISSUE TITLE
Upload Point Cloud Into WebODM

### ISSUE THREAD

**Issue by TheDiscordian** [OpenDroneMap/WebODM#965]
### What is the problem?

I want to upload a `las` file and view it, but the feature is not available it seems.

### What should be the expected behavior?

Upload `las` and view the data in Potree.

### More info

I stumbled upon this old thread: https://community.opendronemap.org/t/upload-point-cloud-into-webodm/852

I'd love to be able to upload `las` files at the very least, to be able to view the data in Potree using WebODM. What ever came of this idea, or what needs to be done? I'd be happy to look into this if pointed in the right direction.

**Comment by pierotofy** [comment]
Hi @TheDiscordian,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-03-05 12:30) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
