### ISSUE TITLE
Broken ubuntugis repo

### ISSUE THREAD

**Issue by pvgmenegasso** [OpenDroneMap/WebODM#986]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Running Ubuntu 20.04. Not really using a browser since this is a build related issue

### What is the problem?

Hello, I cannot currently run ./webodm.sh rebuild because apparently the ubuntugis ppa cannot be found.

### Any helps with this issue ? Are you able to reproduce it ?
Yes, just running ./webodm.sh rebuild

### What should be the expected behavior?

It should build without errors, right ?

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Just ran ./webodm.sh rebuild

**Comment by pierotofy** [comment]
Hi @pvgmenegasso,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-05-14 15:55) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by pvgmenegasso** [comment]
Hey Piero, apparently it was a network environment issue. I was able to solve it. Thanks a lot and sorry for bothering :P

**Comment by pierotofy** [comment]
Glad to hear! No worries, thanks for updating the issue thread.
