### ISSUE TITLE
Processing Node not available for non-Admin despite permissions

### ISSUE THREAD

**Issue by ntrip6** [OpenDroneMap/WebODM#987]
Hello, 
I've been successfully using WebODM (via Docker on an Ubuntu VM) and one project processed beautifully using the Admin account. Now I've got a non-Admin user wanting to use it but they don't see any processing nodes. 
I gave them all permissions (and staff status, but not SU), and so they should be able to add/use nodes but they see none.
I added them using the existing node-1 settings that works for Admin but no luck.
I tried restarting the whole app (./webodm start) with no effect.
As you can see in this screenshot I've now added many nodes but none show up on as Available except in the Admin user. Thanks 
![image](https://user-images.githubusercontent.com/480545/118554198-ff476f80-b715-11eb-8363-2d87d6e89e25.png)

**Comment by pierotofy** [comment]
Hi @ntrip6,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2021-05-18 16:50) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by smathermather** [comment]
Come on over to community.opendronemap.org for support questions. We try to keep the issue queue for bugs and enhancements.

**Comment by ntrip6** [comment]
Well I've tried a variety of things and this seems like perhaps a bug in the node permissions. If not maybe someone will explain in the community forums.

**Comment by ntrip6** [comment]
Granting the user SU privileges solves it. Not ideal but it'll do for now.
